#!/usr/bin/env bash
# configuring web-01 to have an HTTP response header

# updating packages
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index page
echo "Hello world!" | sudo tee /var/www/html/index.html

# performing a redirection
new_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Mark-Tevin permanent;"

sudo sed -i "s/server_name _;/$new_str/" /etc/nginx/sites-enabled/default

# Creating a custom error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Custom HTTP Response Header

sudo sed -1 "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test for syntax errors
sudo nginx -t

# Restart nginx service
sudo service nginx restart
