#!/usr/bin/env bash
# Nginx likes port 80
# configuring a nginx server to listen to port 80

#remove the default nginx configuration file
rm /etc/nginx/sites-enabled/default
# configure Nginx to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
