#!/usr/bin/env bash
# Bash script that loops from 1 to 10, 
# displays bad luck for the 4th, 
# good luck for the 8th, other Best School

counter=0

while [ $counter -le 10 ];
do
    if [ $counter -eq 4 ];
then
        echo "bad luck"
    elif [ $counter -eq 8 ];
then
        echo "good luck"
    else
        echo "Best School"
    fi
    counter=$((counter + 1))
done
