#!/usr/bin/env bash
# Configures Ubuntu server and resolves localhost and facebook.com

cp /etc/hosts ~/hosts.new
# update local host resolution
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
# update facebook.com resolution
sed -i 's/^.*facebook\.com.*$/8.8.8.8 facebook.com/' ~/hosts.new
# overwrite the original host file with the updated one
cp -f ~/hosts.new /etc/hosts
