#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu
# ssh -i ~/.ssh/school ubuntu@18.209.225.168
ssh -i /root/.ssh/id_rsa ubuntu@18.209.225.168
